project:
  type: book

book:
  title: "Oxinfer onboarding"
  author: "Danielle Newby, Martí Català, Edward Burn"
  date: today
  chapters:
  - index.qmd
  - chapters/the_team.qmd
  - chapters/epi_basis.qmd
  - chapters/omop.qmd
  - chapters/R_basis.qmd
  - chapters/databases_and_servers.qmd
  - chapters/connect_to_database.qmd
  - chapters/github.qmd
  - chapters/studies_and_authorship.qmd
  - chapters/useful_contacts.qmd
  - chapters/useful_terms.qmd
  - chapters/checklist.qmd
  - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

number-sections: true
