project:
  type: book

book:
  title: "Oxinfer onboarding"
  author: "Danielle Newby, Martí Català, Edward Burn"
  date: today
  chapters:
  - index.qmd
  - the_team.qmd
  - useful_contacts.qmd
  - connect_to_database.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual


  
