project:
  type: book

book:
  title: "Oxinfer onboarding"
  author: "Danielle Newby, Martí Català, Edward Burn"
  date: today
  chapters:
  - index.qmd
  - the_team.qmd
  - epi_basis.qmd
  - omop.qmd
  - R_basis.qmd
  - databases_and_servers.qmd
  - connect_to_database.qmd
  - github.qmd
  - studies_and_authorship.qmd
  - useful_contacts.qmd
  - useful_terms.qmd
  - checklist.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

number-sections: true

  
