# Checklist {#sec-checklist}

Have you completed the following tasks?

-   Created a GitHub account

-   Been added to the PDE GitHub account

-   Been added to PDE teams channel and relevant channels (OHDSI server users, Oxinfer, DARWIN etc)

-   Get access to intranet to get documents for information governance training

-   Completed your information governance online training

-   Contacted information governance manager to attend group information governance induction meeting

-   Register and complete CPRD database training (CPRD E-Learning module)

-   Register yourself as a NDORMS CPRD user

-   Got your user account for the servers

-   Set up your R studio environment

-   Completed mandatory health and safety training

-   Write a brief description of yourself and how you like to work to be included in the group website.

-   Download GitHub Desktop.

-   Been invited to the PDE meetings (Mahki).

-   Been invited to the OxInfer meetings (Ed).

-   Book a photo session to update your photo on the website and edit your description.
